### ISSUE TITLE
Search Functionality Does Not Work as Expected

### ISSUE THREAD

**Issue by alexlee-dev** [grommet/grommet-icons-site#11]
I believe the state is being reset when the header at the top refreshes. Try searching for Group, and it doesn't give you group. But search for User and it gives you Group.

Some icons do not show up when you search for them.

Sometimes you search and the results refresh after the header has refreshed, but the input of the searchbar remains the same.

**Comment by ericsoderberghp** [comment]
Fixed in https://github.com/grommet/grommet-icons-site/commit/a11060559c45737f5a150e2e3036c0d8cd5c3340

**Comment by alexlee-dev** [comment]
Thank you!
