### ISSUE TITLE
prod site throws react error that turns entire page white

### ISSUE THREAD

**Issue by samuelgoff** [grommet/grommet-icons-site#38]
I found a bug on icons.grommet.io which consistently turns the entire page white, when you try to scroll down to the bottom of the page. This happens in both Chrome (Version 92.0.4515.159 (Official Build) (x86_64)) & Safari (v14.1.2), latest versions. Breaks the entire page.

> Error: Minified React error #130; visit [https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=object&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Seems like it might be related to virtual scrolling, but haven’t investigated thoroughly.
![Screen Shot 2021-08-30 at 3 17 21 PM](https://user-images.githubusercontent.com/2007084/131403901-5ac4887a-ee7d-4234-853e-fb610b2bd1e5.png)
![Screen Shot 2021-08-30 at 3 33 49 PM](https://user-images.githubusercontent.com/2007084/131403912-55b8d890-3b45-4365-a395-b845445ff5d5.png)

**Comment by MikeKingdom** [comment]
InfiniteScroll.js is calling `setRenderPageBounds([undefined, undefined])` and this is down in React somewhere during that call. renderPageBounds is [0,11] at the time (startPage 0, endPage 11). I don't know why yet.

**Comment by MikeKingdom** [comment]
grommet-icons-site is grabbing themes/base.js and trying to use it as an Icon React component in the grid of icons it renders. When it hits that and tries to render it, it fails since it's not a React component.
