### ISSUE TITLE
Site breaks after certain scrolled distance

### ISSUE THREAD

**Issue by nakaz** [grommet/grommet-icons-site#8]
Breakage occurs after scrolling down a certain length of the site. 

When scrolling down through all the icons, around the "S" or "T" lettered icons, the site will break into a blank page. 

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

**Comment by ericsoderberghp** [comment]
Fixed in https://github.com/grommet/grommet-icons-site/pull/10
