### ISSUE TITLE
Searching "ba" crashes React

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-icons-site#9]
Searching `ba` on the grommet icons site crashes React. Interestingly enough, [Initial render](http://grommet.io/grommet-icons/?s=ba) of a `ba` search renders fine.

**Comment by alansouzati** [comment]
weird! let me take a look at this.

**Comment by ericsoderberghp** [comment]
Fixed in https://github.com/grommet/grommet-icons-site/pull/10
